spring:
  config:
    import: application-oauth.yml
  datasource:
    url: jdbc:mariadb://${HOST}:3306/peerna
    username: ${USERNAME}
    password: ${PASSWORD}
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
    check-template-location: true
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
logging.level:
  cos.peerna: info
  org:
    hibernate:
      SQL: info
      orm.jdbc.bind: trace
    springframework:
      security: TRACE
      data:
        redis:
          core:
            RedisTemplate: debug

server:
  error:
    include-stacktrace: on_param
    include-message: always
cloud:
  aws:
    credentials:
      instance-profile: true
    s3:
      bucket: peerna-bucket
    stack:
      auto: false
