spring:
  config:
    import: application-oauth.yml
  datasource:
    url: jdbc:mariadb://${HOST}:3306/peerna
    username: ${USERNAME}
    password: ${PASSWORD}
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
    check-template-location: true
  data:
    redis:
      host: localhost
      port: 6379
logging.level:
  cos.peerna: info
  org.hibernate.SQL: info
  org.hibernate.orm.jdbc.bind: trace
  org.springframework.security: TRACE
server:
  error:
    include-stacktrace: on_param
  servlet:
    session:
      cookie:
        secure: true
        same-site: none
        max-age: 7200

