spring: #띄어쓰기 없음
  config:
    import: application-oauth.yml
  datasource: #띄어쓰기 2칸
    url: jdbc:mariadb://localhost:3306/peerna
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa: #띄어쓰기 2칸
    hibernate: #띄어쓰기 4칸
      ddl-auto: create #띄어쓰기 6칸
    properties: #띄어쓰기 4칸
      hibernate: #띄어쓰기 6칸
        # show_sql: true #띄어쓰기 8칸
        format_sql: true #띄어쓰기 8칸
        default_batch_fetch_size: 1000
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
    check-template-location: true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6
server:
  error:
    include-stacktrace: on_param
